// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type CreateUsersWithListInputResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	User *components.User
}

func (c *CreateUsersWithListInputResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUsersWithListInputResponse) GetUser() *components.User {
	if c == nil {
		return nil
	}
	return c.User
}
