// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type DeleteUserRequest struct {
	// The name that needs to be deleted
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (d *DeleteUserRequest) GetUsername() string {
	if d == nil {
		return ""
	}
	return d.Username
}

type DeleteUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User deleted
	User *components.User
}

func (d *DeleteUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteUserResponse) GetUser() *components.User {
	if d == nil {
		return nil
	}
	return d.User
}
