// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type FindPetsByTagsRequest struct {
	// Tags to filter by
	Tags []string `queryParam:"style=form,explode=true,name=tags"`
}

func (f *FindPetsByTagsRequest) GetTags() []string {
	if f == nil {
		return nil
	}
	return f.Tags
}

type FindPetsByTagsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Pets []components.Pet
}

func (f *FindPetsByTagsResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FindPetsByTagsResponse) GetPets() []components.Pet {
	if f == nil {
		return nil
	}
	return f.Pets
}
