// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type GetInventoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Object map[string]int
}

func (g *GetInventoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInventoryResponse) GetObject() map[string]int {
	if g == nil {
		return nil
	}
	return g.Object
}
