// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type GetInventoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Object map[string]int
}

func (o *GetInventoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetInventoryResponse) GetObject() map[string]int {
	if o == nil {
		return nil
	}
	return o.Object
}
