// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type UpdateUserRequest struct {
	// name that needs to be updated
	Username string `pathParam:"style=simple,explode=false,name=username"`
	// Update an existent user in the store
	User *components.User `request:"mediaType=application/json"`
}

func (u *UpdateUserRequest) GetUsername() string {
	if u == nil {
		return ""
	}
	return u.Username
}

func (u *UpdateUserRequest) GetUser() *components.User {
	if u == nil {
		return nil
	}
	return u.User
}

type UpdateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (u *UpdateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}
