// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type UploadFileRequest struct {
	// ID of pet to update
	PetID int64 `pathParam:"style=simple,explode=false,name=petId"`
	// Additional Metadata
	AdditionalMetadata *string `queryParam:"style=form,explode=true,name=additionalMetadata"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	RequestBody *any `request:"mediaType=application/octet-stream"`
}

func (u *UploadFileRequest) GetPetID() int64 {
	if u == nil {
		return 0
	}
	return u.PetID
}

func (u *UploadFileRequest) GetAdditionalMetadata() *string {
	if u == nil {
		return nil
	}
	return u.AdditionalMetadata
}

func (u *UploadFileRequest) GetRequestBody() *any {
	if u == nil {
		return nil
	}
	return u.RequestBody
}

type UploadFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	APIResponse *components.APIResponse
}

func (u *UploadFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UploadFileResponse) GetAPIResponse() *components.APIResponse {
	if u == nil {
		return nil
	}
	return u.APIResponse
}
