// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/jamietanna/speakeasy-example-spec/models/components"
)

type UploadFileRequest struct {
	// ID of pet to update
	PetID int64 `pathParam:"style=simple,explode=false,name=petId"`
	// Additional Metadata
	AdditionalMetadata *string `queryParam:"style=form,explode=true,name=additionalMetadata"`
	RequestBody        []byte  `request:"mediaType=application/octet-stream"`
}

func (o *UploadFileRequest) GetPetID() int64 {
	if o == nil {
		return 0
	}
	return o.PetID
}

func (o *UploadFileRequest) GetAdditionalMetadata() *string {
	if o == nil {
		return nil
	}
	return o.AdditionalMetadata
}

func (o *UploadFileRequest) GetRequestBody() []byte {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type UploadFileResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful operation
	APIResponse *components.APIResponse
}

func (o *UploadFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UploadFileResponse) GetAPIResponse() *components.APIResponse {
	if o == nil {
		return nil
	}
	return o.APIResponse
}
