// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// APIErrorUnauthorized - Unauthorized error
type APIErrorUnauthorized struct {
	Status int    `json:"status"`
	Error_ string `json:"error"`
}

var _ error = &APIErrorUnauthorized{}

func (e *APIErrorUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
