// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// APIErrorInvalidInput - Not Found error
type APIErrorInvalidInput struct {
	Status int    `json:"status"`
	Error_ string `json:"error"`
}

var _ error = &APIErrorInvalidInput{}

func (e *APIErrorInvalidInput) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
