// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APIResponse struct {
	Code    *int    `json:"code,omitempty"`
	Type    *string `json:"type,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (a *APIResponse) GetCode() *int {
	if a == nil {
		return nil
	}
	return a.Code
}

func (a *APIResponse) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *APIResponse) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}
