// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type User struct {
	ID        *int64  `json:"id,omitempty"`
	Username  *string `json:"username,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	// User Status
	UserStatus *int `json:"userStatus,omitempty"`
}

func (u *User) GetID() *int64 {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *User) GetUsername() *string {
	if u == nil {
		return nil
	}
	return u.Username
}

func (u *User) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

func (u *User) GetLastName() *string {
	if u == nil {
		return nil
	}
	return u.LastName
}

func (u *User) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *User) GetPassword() *string {
	if u == nil {
		return nil
	}
	return u.Password
}

func (u *User) GetPhone() *string {
	if u == nil {
		return nil
	}
	return u.Phone
}

func (u *User) GetUserStatus() *int {
	if u == nil {
		return nil
	}
	return u.UserStatus
}
