workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-first-source:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/jamietanna/jamietanna/my-first-source
targets:
    my-first-target:
        target: go
        source: my-first-source
